// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddConnection'](arg1, arg2, arg3, arg4);
}

export function ConnectToMySQL(arg1) {
  return window['go']['main']['App']['ConnectToMySQL'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteTableData(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteTableData'](arg1, arg2, arg3);
}

export function ExecuteQuery(arg1, arg2) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetDatabases() {
  return window['go']['main']['App']['GetDatabases']();
}

export function GetTableData(arg1, arg2) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2);
}

export function GetTables(arg1) {
  return window['go']['main']['App']['GetTables'](arg1);
}

export function InsertTableData(arg1, arg2, arg3) {
  return window['go']['main']['App']['InsertTableData'](arg1, arg2, arg3);
}

export function UpdateTableData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTableData'](arg1, arg2, arg3, arg4);
}
