// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToMySQL(arg1:string):Promise<void>;

export function DeleteTableData(arg1:string,arg2:string,arg3:number):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<Array<{[key: string]: any}>>;

export function GetDatabases():Promise<Array<string>>;

export function GetTableData(arg1:string,arg2:string):Promise<Array<{[key: string]: any}>>;

export function GetTables(arg1:string):Promise<Array<string>>;

export function InsertTableData(arg1:string,arg2:string,arg3:{[key: string]: any}):Promise<void>;

export function UpdateTableData(arg1:string,arg2:string,arg3:number,arg4:{[key: string]: any}):Promise<void>;
